# 生产环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://172.19.181.191:3306/modulithshop_mal?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&&zeroDateTimeBehavior=convertToNull
    username: modulithshop_mal
    password: 6zas43S3aNFFwrzF
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 172.19.181.191 # Redis服务器地址
    database: 10 # Redis数据库索引（默认为0）
    database-data: 11 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: dev_pwd_123 # Redis服务器连接密码（默认为空）
    timeout: 60s # 连接超时时间（毫秒） 3000ms
# 日志配置
logging:
  file:
    name: dev_shop_suite.log
  level:
    root: WARN
    com.suisung.shopsuite: ERROR
    com.baomidou.mybatisplus: ERROR



url:
  base: https://demo.modulithshop.cn
  static: ${url.api.admin}
  pc: ${url.base}/pc
  h5: ${url.base}/h5
  admin: ${url.base}/admin
  api:
    manage: ${url.base}/manage
    front: ${url.base}/front

  websocket-url: wss://im.suteshop.com:9501
static:
  file:
    path: /opt/apps/mall/public/static
    url: ${url.api.front}/front/static
mall:
  socket:
    url: wss://demo.mallsuite.cn/mallsuiteImSocketServer

upload:
  # 文件上传磁盘位置 d:/public/uploads
  dir: ""
  dir-index: 0

  # 上传附件访问网址
  web-url: ${url.base}

  #文件上传是否使用uuid命名
  uuid-name: true


  #文件上传生成缩略图的大小(kb)
  thumbnail-size: 60

  #OpenOffice的安装目录
  open-office-home: C:/OpenOffice4/

  # 本地环境静态文件路径
  filepath: D:/wwwroot/mall/public/static/
