# 开发环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.100.28.2:3306/dev_shop_suite?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&&zeroDateTimeBehavior=convertToNull
    username: store
    password: storefhwui!#2sf13f
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 10 # Redis数据库索引（默认为0）
    database-data: 11 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: dev_pwd_123 # Redis服务器连接密码（默认为空）
    timeout: 60s # 连接超时时间（毫秒）3000ms
# 日志配置
logging:
  level:
    com.suisung.shopsuite: INFO
    com.baomidou.mybatisplus: INFO


url:
  base: "http://127.0.0.1:${server.port}"
  pc: "http://localhost:5173"
  h5: "http://localhost:8080/h5"
  admin: "http://localhost:15000"
  api:
    manage: ${url.base}/manage
    front: ${url.base}/front

  websocket-url: wss://im.suteshop.com:9501
static:
  file:
    path: /opt/apps/mall/public/static
    url: ${url.api.front}/front/static
mall:
  socket:
    url: wss://demo.mallsuite.cn/mallsuiteImSocketServer

upload:
  # 文件上传磁盘位置 d:/public/uploads
  dir: ""
  dir-index: 0

  # 上传附件访问网址
  web-url: ${url.base}

  #文件上传是否使用uuid命名
  uuid-name: true


  #文件上传生成缩略图的大小(kb)
  thumbnail-size: 60

  #OpenOffice的安装目录
  open-office-home: C:/OpenOffice4/

  # 本地环境静态文件路径
  filepath: D:/wwwroot/mall/public/static/
